### ISSUE TITLE
[Wikidata] Json dumps import.

### ISSUE THREAD

**Issue by SergeC** [elastic/stream2es#43]
Hi. Can you please add import of json dumps from https://dumps.wikimedia.org/other/wikidata/ ?
Or in case if it possible to load via stdin please provide me some instructions.

**Comment by drewr** [comment]
I haven't retrieved one of those archives before. What JSON format do they use? If it's jsonlines, then it would just be a matter of `curl -s https://dumps.wikimedia.org/other/wikidata/20150504.json.gz | stream2es --log debug`. If they put all the content in a single data structure you'll need a streaming JSON parser, for which there isn't a stream2es stream yet.

**Comment by drewr** [comment]
That would involve a streaming JSON parser. What's the problem with the integrated `wiki` stream?

**Comment by diadistis** [comment]
A bit too late maybe, but I'll post it anyway for anyone who might find this one-liner for importing wikidata useful: `curl -s http://dumps.wikimedia.org/other/wikidata/20150810.json.gz | zcat | sed 's/,$//' | sed '/^\(\[\|\]\)$/d' | stream2es stdin --target http://xxx:9200/index/target`

**Comment by parasitid** [comment]
you could use the 'jq' tool to process these lines instead of seds. with the --stream opt to process huge files.

curl -s http://dumps.wikimedia.org/other/wikidata/20150810.json.gz | zcat | jq -nc -r --stream 'fromstream(1|truncate_stream(inputs)) | ...
