### ISSUE TITLE
Stream2es refrence for learning

### ISSUE THREAD

**Issue by DBARUNNER** [elastic/stream2es#64]
if you give me please a refrence of docmentation to learn stream2es of any book

**Comment by drewr** [comment]
Hi @DBARUNNER! There is not a book on stream2es.  The best place for documentation is the [readme](https://github.com/elastic/stream2es/blob/master/README.md), which tries to be as comprehensible as possible.  I would also take a look [Logstash](https://www.elastic.co/products/logstash) and [Beats](https://www.elastic.co/products/beats), as they can now do many of the things that stream2es originally aimed to do.
